#spring:
#  config:
#    activate:
#      on-profile: "qa"

build:
  version: "2.0"

loan:
  message: "Welcome to loan account related QA APIs "
  contactDetails:
    name: "Emma - QA Lead"
    email: "emma@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371