server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:card
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  config:
#    import:
#      - "application-qa.yml"
#      - "application-prd.yml"
#    profiles:
#      active:
#        - "qa"

build:
  version: "3.0"

card:
  message: "Welcome to card account related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345