# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: patelnisargm/config-server
  tag: 4.2

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
discovery_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false