server:
  port: 8070

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/patelnisargm/spring-boot-lab.git"
          searchPaths: microservices/config-server/src/main/resources/config
          default-label: R1.0
          timeout: 5
          clone-on-start: true
          force-pull: true
