services:
  account:
    image: "patelnisargm/account:4.1"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loan:
    image: "patelnisargm/loan:4.1"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  card:
    image: "patelnisargm/card:4.1"
    container_name: card-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
  bank:
    driver: "bridge"